### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by montyclt** [iokode/OpinionatedFramework#11]
# Architecture
- [ ] Remove contracts directory. Set each contract in its own directory.

# Core
- [ ] Events – dispatching and handling events.
- [ ] Jobs – scheduling and enqueuing jobs.
- [ ] Notifications – dispatching and reading notifications.
- [ ] Persistence – supports UoW and event sourcing patterns.
- [ ] Text translator

# Mail
- [ ] Email builder.
- [ ] Log email contact implementation.

# Configuration
- [ ] Configuration.

# ASP.NET Core integration
- [ ] Generate rest controllers for commands.
- [ ] Generate gRPC endpoints for commands.
- [ ] Set session data from request into command share data.
